
# POST https://api.openai.com/v1/chat/completions


POST https://chat.lazaytools.top/api/v1/chat/completions
content-type: application/json
Authorization: Bearer lazybox-YfJipx8QHYp8OpEKVjoHos88g

{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "Who won the world series in 2020?"
        },
        {
            "role": "assistant",
            "content": "The Los Angeles Dodgers won the World Series in 2020."
        },
        {
            "role": "user",
            "content": "Where was it played?"
        }
    ],
    "temperature": 1,
    "top_p": 1,
    "n": 1,
    "stream": false,
    "max_tokens": 250,
    "presence_penalty": 0,
    "frequency_penalty": 0
}

###

POST https://gpt.visa-99.top/api/v1/chat/completions
content-type: application/json
Authorization: Bearer fastgpt-3xgXbDwBHcb7ii9gBDM583kDHxYKEbG6eaHWAWjNPaFc1vaQB0Tn9uQmXG

{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "Who won the world series in 2020?"
        },
        {
            "role": "assistant",
            "content": "The Los Angeles Dodgers won the World Series in 2020."
        },
        {
            "role": "user",
            "content": "Where was it played?"
        }
    ],
    "temperature": 1,
    "top_p": 1,
    "n": 1,
    "stream": false,
    "max_tokens": 250,
    "presence_penalty": 0,
    "frequency_penalty": 0
}

###

POST https://api.dify.ai/v1/chat-messages
content-type: application/json
authorization: Bearer app-5uPNxwQ6Q8bU6FzO3WZ72tqV

{
    "inputs": {},
    "response_mode": "streaming",
    "user": "apiuser",
    "query": "Who won the world series in 2020?"
}

###

POST http://chat.wangpisi.com/v1/chat-messages
content-type: application/json
Authorization: Bearer app-voGEBvo8IYKmymYkVtBgxBFF

{
    "inputs": {},
    "response_mode": "blocking",
    "user": "apiuser",
    "query": "Who won the world series in 2020?"
}