import { Platform } from '../types';

export const ALL_PLATFORMS: Platform[] = [
  {
    id: 'sannysoft',
    type: 'OTHER',
    name: 'Sannysoft',
    avatar: '',
    desc: '',
    impl: true,
  },
  {
    id: 'bilibili',
    type: 'HOT',
    name: '哔哩哔哩',
    avatar: 'https://bilibili.com/favicon.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'zhihu',
    type: 'ME_MEDIA',
    name: '知乎',
    avatar: 'https://www.zhihu.com/favicon.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'test',
    type: 'OTHER',
    name: 'Test',
    avatar: '',
    desc: '',
    impl: true,
  },
  {
    id: 'jinritemai',
    type: 'E_COMMERCE',
    name: '抖店',
    avatar:
      'https://lf3-static.bytednsdoc.com/obj/eden-cn/yvahlyj_upfbvk_zlp/ljhwZthlaukjlkulzlp/pc_creator/favicon_v2_7145ff0.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'douyin',
    type: 'ME_MEDIA',
    name: '抖音',
    avatar:
      'https://lf3-static.bytednsdoc.com/obj/eden-cn/yvahlyj_upfbvk_zlp/ljhwZthlaukjlkulzlp/pc_creator/favicon_v2_7145ff0.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'baijiahao',
    type: 'ME_MEDIA',
    name: '百家号',
    avatar: 'https://baijiahao.baidu.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'buyin_jinritemai',
    type: 'ME_MEDIA',
    name: '百应巨量',
    avatar: 'https://buyin.jinritemai.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'douyin_mp',
    type: 'ME_MEDIA',
    name: '抖音企业号',
    avatar: 'https://buyin.jinritemai.com/favicon.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'ctrip_imvendor',
    type: 'HOT',
    name: '携程供应商',
    avatar: 'https://ctrip.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'dianping',
    type: 'E_COMMERCE',
    name: '美团开店宝',
    avatar: 'https://awp-assets.meituan.net/nibfe/epassport-html/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'findlaw',
    type: 'LAW',
    name: '找法网',
    avatar: 'https://findlaw.cn/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'lawtime',
    type: 'LAW',
    name: '法律快车',
    avatar: 'https://lawtime.cn/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'lvlin',
    type: 'LAW',
    name: '律临',
    avatar: 'https://lvlin-base.cdn.bcebos.com/sp-saas/common/ae_logo.png',
    desc: '',
    impl: false,
  },
  {
    id: 'meituan_mtm',
    type: 'E_COMMERCE',
    name: '美团电商',
    avatar:
      'https://p0.meituan.net/publiconline/62580fcd548dba6697eb64f2769cc9b21804.png',
    desc: '',
    impl: false,
  },
  {
    id: 'meituan_my',
    type: 'E_COMMERCE',
    name: '美团买药',
    avatar: 'https://epassport.meituan.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'meituan',
    type: 'ME_MEDIA',
    name: '美团直播助手',
    avatar: 'https://live.meituan.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'oceanengine',
    type: 'E_COMMERCE',
    name: '小6客服',
    avatar: 'https://sf1-cdn-tos.toutiaostatic.com/obj/ttfe/cg/fe/im/im.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'pinduoduo',
    type: 'E_COMMERCE',
    name: '拼多多',
    avatar: 'https://mms.pinduoduo.com/login/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'toutiao',
    type: 'ME_MEDIA',
    name: '头条号',
    avatar: 'https://sf3-cdn-tos.toutiaostatic.com/obj/mp/logo-toutiao.png',
    desc: '',
    impl: false,
  },
  {
    id: '51job',
    type: 'RECRUIT',
    name: '前程无忧',
    avatar: 'https://ehire.51job.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: '58',
    type: 'RECRUIT',
    name: '58同城',
    avatar: 'https://passport.58.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: '66law',
    type: 'LAW',
    name: '华律',
    avatar: 'https://login.66law.cn/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: '1688',
    type: 'E_COMMERCE',
    name: '1688 找工厂',
    avatar: 'https://img.alicdn.com/tfs/TB1uh..zbj1gK0jSZFuXXcrHpXa-16-16.ico',
    desc: '',
    impl: false,
  },
  {
    id: '64365',
    type: 'LAW',
    name: '律图律师',
    avatar: 'https://login.64365.com/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'weibo',
    type: 'HOT',
    name: '微博私信',
    avatar: 'https://conchfairy.sinajs.cn/chat/favicon.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'whatsapp',
    type: 'HOT',
    name: 'Whatsapp',
    avatar: 'https://web.whatsapp.com/img/favicon/1x/favicon.png',
    desc: '',
    impl: false,
  },
  {
    id: 'weixin_channels',
    type: 'ME_MEDIA',
    name: '微信视频号',
    avatar:
      'https://res.wx.qq.com/t/wx_fed/finder/helper/finder-helper-web/res/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'xiaohongshu_pro',
    type: 'ME_MEDIA',
    name: '小红书私信',
    avatar: 'https://www.xiaohongshu.com/favicon.ico',
    desc: '\n### 小红书平台支持\n\n发送关联链接(笔记、商品)，可以使用以下规则编写回复：\n\n```\n【g-数字】：关联商品\n【n-数字】：关联笔记\n\n这个数字是商品或者笔记所在页面的排序\n```\n\n例如：【g-1】是指第一条关联商品，【n-2】是第二条关联笔记，\n\n如果要连发两条后再混着一条文案回复可以这样写: `【g-1】|【n-2】|你好`，这样就会先发送 【g-1】商品，然后发送【n-2】商品，最后发送“你好”。\n',
    impl: true,
  },
  {
    id: 'xiaohongshu',
    type: 'ME_MEDIA',
    name: '小红书评论',
    avatar: 'https://www.xiaohongshu.com/favicon.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'zhuxiaobang',
    type: 'HOT',
    name: '住小帮',
    avatar:
      'https://lf3-static.bytednsdoc.com/obj/eden-cn/jpahaz_lm_kltvo/ljhwZthlaukjlkulzlp/homed_merchant_admin/favicon.ico',
    desc: '',
    impl: false,
  },
  {
    id: 'nowsecure',
    type: 'OTHER',
    name: 'nowsecure',
    avatar: '',
    desc: '',
    impl: false,
  },
  {
    id: 'antoinevastel',
    type: 'OTHER',
    name: 'antoinevastel',
    avatar: '',
    desc: '',
    impl: false,
  },
  {
    id: 'fingerprintjs',
    type: 'OTHER',
    name: 'fingerprintjs',
    avatar: '',
    desc: '',
    impl: false,
  },
  {
    id: 'incolumitas',
    type: 'OTHER',
    name: 'incolumitas',
    avatar: '',
    desc: '',
    impl: false,
  },
  {
    id: 'recaptcha',
    type: 'OTHER',
    name: 'recaptcha',
    avatar: '',
    desc: '',
    impl: false,
  },
  {
    id: 'win_wechat',
    type: 'HOT',
    name: '微信',
    avatar: 'https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'win_wecom',
    type: 'HOT',
    name: '企业微信(Bate版)',
    avatar:
      'https://wwcdn.weixin.qq.com/node/wwnl/wwnl/style/images/independent/favicon/favicon_32h$a41a4426.png',
    desc: '',
    impl: false,
  },
  {
    id: 'win_qianniu',
    type: 'E_COMMERCE',
    name: '千牛',
    avatar: 'https://qianniu.1688.com/favicon.ico',
    desc: '',
    impl: true,
  },
  {
    id: 'win_jinmai',
    type: 'E_COMMERCE',
    name: '京卖',
    avatar: 'https://shop.jd.com/jdm/favicon.ico',
    desc: '',
    impl: true,
  },
];
